import{a as m,S,i as f}from"./assets/vendor-7e69f3e5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();m.defaults.headers.common["x-api-key"]="live_URYiUDVMJKnsTYSLnYWeR31PUeH8c5Yz2b0ev0a1MU6oS9U6mrAOkeE6lCc4s4wU";async function w(){return await m.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function v(e){return await m.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(t=>t.data)}const I="/cats-api/assets/no_image-6398502d.png",u=document.getElementById("breed-select"),i=document.querySelector(".cat-info"),l=document.querySelector(".spinner"),x=new S({select:u,settings:{placeholderText:"Search breeds"}}),g={title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topRight",color:"red"};function p(e){e.style.display="flex"}function d(e){e.style.display="none"}function C(e){const t=e[0].breeds[0];i.innerHTML=`
    <div class="wrapper">
      <img class="cat-img" src="${e[0].url}" alt="Cat Image"/>
      <div>
        <h2>${t.name}</h2>
        <article><b>Description:</b> ${t.description}</article><br>
        <article><b>Temperament:</b> ${t.temperament}</article><br>
        <article><b>Country:</b> ${t.origin}</article>
        <img src="https://flagsapi.com/${t.country_code}/shiny/64.png" onerror="src='${I}'" width="64px" alt="country flag"> 
      </div>
    </div>
  `,p(i)}async function E(){try{const e=u.value;d(i),p(l);const t=await v(e);C(t)}catch{f.show(g)}finally{d(l)}}async function $(){try{const t=(await w()).map(({id:o,name:s})=>({text:s,value:o}));x.setData([{placeholder:!0,text:""},...t]),u.addEventListener("change",E)}catch{f.show(g)}finally{d(l)}}$();const h=6,L=document.querySelector(".hour"),O=document.querySelector(".min"),B=document.querySelector(".sec"),y=()=>{let e=new Date,t=e.getHours()*30,o=e.getMinutes()*h,s=e.getSeconds()*h;L.style.transform=`rotateZ(${t+o/12}deg)`,O.style.transform=`rotateZ(${o}deg)`,B.style.transform=`rotateZ(${s}deg)`};y();setInterval(y,1e3);const T=e=>{const t=e.target;t.textContent.toLowerCase()==="light"?(t.textContent="dark",localStorage.setItem("theme","dark"),document.documentElement.setAttribute("data-theme","dark")):(t.textContent="light",localStorage.setItem("theme","light"),document.documentElement.setAttribute("data-theme","light"))},b=document.querySelector(".switch-btn");b.addEventListener("click",T,!1);let c="dark";c=localStorage.getItem("theme")?localStorage.getItem("theme"):null;c&&(document.documentElement.setAttribute("data-theme",c),b.textContent=c);
//# sourceMappingURL=commonHelpers.js.map
