import{a as d,S as w,i as p}from"./assets/vendor-7e69f3e5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();d.defaults.headers.common["x-api-key"]="live_URYiUDVMJKnsTYSLnYWeR31PUeH8c5Yz2b0ev0a1MU6oS9U6mrAOkeE6lCc4s4wU";async function S(){return await d.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function v(e){return await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(t=>t.data)}const x="/cats-api/assets/no_image-6398502d.png",u=document.getElementById("breed-select"),i=document.querySelector(".cat-info"),a=document.querySelector(".spinner"),C=new w({select:u,settings:{placeholderText:"Search breeds"}}),f={title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!",position:"topRight",color:"red"};function g(e){e.style.display="flex"}function l(e){e.style.display="none"}function E(e){const t=e[0].breeds[0];i.innerHTML=`
    <div class="wrapper">
      <img class="cat-img" src="${e[0].url}" alt="Cat Image"/>
      <div>
        <h2>${t.name}</h2>
        <article><b>Description:</b> ${t.description}</article><br>
        <article><b>Temperament:</b> ${t.temperament}</article><br>
        <article><b>Country:</b> ${t.origin}</article>
        <img src="https://flagsapi.com/${t.country_code}/shiny/64.png" onerror="src='${x}'" width="64px" alt="country flag"> 
      </div>
    </div>
  `,g(i)}async function $(){try{const e=u.value;l(i),g(a);const t=await v(e);E(t)}catch{p.show(f)}finally{l(a)}}async function L(){try{const t=(await S()).map(({id:o,name:s})=>({text:s,value:o}));C.setData([{placeholder:!0,text:""},...t]),u.addEventListener("change",$)}catch{p.show(f)}finally{l(a)}}L();const m=6,O=document.querySelector(".hour"),B=document.querySelector(".min"),I=document.querySelector(".sec"),y=()=>{let e=new Date,t=e.getHours()*30,o=e.getMinutes()*m,s=e.getSeconds()*m;O.style.transform=`rotateZ(${t+o/12}deg)`,B.style.transform=`rotateZ(${o}deg)`,I.style.transform=`rotateZ(${s}deg)`};y();setInterval(y,1e3);const T=e=>{const t=e.target;t.textContent.toLowerCase()==="light"?(t.textContent="dark",document.documentElement.setAttribute("data-theme","dark")):(t.textContent="light",document.documentElement.setAttribute("data-theme","light"))},b=document.querySelector(".switch-btn");b.addEventListener("click",T,!1);let h="dark";document.documentElement.setAttribute("data-theme",h),b.textContent=h;
//# sourceMappingURL=commonHelpers.js.map
